/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mfeanurrkllcqqqqugda"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZWFudXJya2xsY3FxcXF1Z2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMzg2ODQsImV4cCI6MjA3OTYxNDY4NH0.-Voh-3O2rjq2VFIlqq16inyPkn02efBcJ06wSVAo9S0"